### ISSUE TITLE
Update checker can't check the plugin version

### ISSUE THREAD

**Issue by pierrealexaline** [cmb69/coco_xh#8]
Coco seem to be not recognized by update checker. When i launch the plugin version checker, i've an error from checker : "Can't check coco"

**Comment by cmb69** [comment]
Sorry, I've totally missed this!

Anyhow, the update check should work since the [respective file](https://raw.githubusercontent.com/cmb69/coco_xh/master/version.nfo) is generally available; however, there are known issues with the update check plugin, and it is probably best to point the version check to GitHub, i.e. replace the contents of your plugins/coco/version.nfo with https://raw.githubusercontent.com/cmb69/coco_xh/76dafea1bd272b44f865358e9495056980c3cd41/version.nfo.
